version: "3.8"

services:
  devnode:
    build:
      context: "."
      dockerfile: "Dockerfile"
      target: "dev"
    command: "tail -F /dev/null"
    volumes:
      - ".:/root/project"
      - "~/.DAP:/root/.DAP" # DAP bind
    working_dir: "/root/project"
    ports:
      - "9229:9229" # debugging port
      - "5173:5173" # vite web server port
      - "4173:4173" # vite web server port
  # devdebugnode:
  #   extends: "devnode"
  #   network_mode: "host" # need to bind host network to debugging using chrome: https://docs.docker.com/network/host/
