version: "3.8"

services:
  devdeno:
    build:
      context: "."
      dockerfile: "Dockerfile"
      target: "dev"
    command: "tail -F /dev/null"
    volumes:
      - ".:/root/project"
    working_dir: "/root/project"
    ports:
      - "9229:9229" # debugging port
